// <auto-generated />
using CoreApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoreApplication.Data.Migrations
{
    [DbContext(typeof(CoreContext))]
    [Migration("20180623201216_LikeEntity")]
    partial class LikeEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AdId");

                    b.Property<string>("ImagePath");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Like", b =>
                {
                    b.Property<int>("LikeeId");

                    b.Property<int>("LikerId");

                    b.HasKey("LikeeId", "LikerId");

                    b.HasIndex("LikerId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.LoginUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Gender");

                    b.Property<string>("Interests");

                    b.Property<string>("Introduction");

                    b.Property<string>("KnownAs");

                    b.Property<DateTime>("LastActive");

                    b.Property<string>("LookingFor");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("LoginUsers");
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<bool>("IsMain");

                    b.Property<int>("LoginUserId");

                    b.Property<string>("PublicId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("LoginUserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Response", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdId");

                    b.Property<string>("FreeText");

                    b.Property<DateTime>("ResponseDate");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AdId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("CoreApplication.Data.Models.Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AdPostDate");

                    b.Property<int>("CategoryId");

                    b.Property<string>("Details");

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<bool>("IsActive");

                    b.Property<double>("Rating");

                    b.Property<string>("Reason");

                    b.Property<string>("Title");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("CoreApplication.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IsValid");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Attachment", b =>
                {
                    b.HasOne("CoreApplication.Data.Models.Ad", "Ad")
                        .WithMany("Attachments")
                        .HasForeignKey("AdId");
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Like", b =>
                {
                    b.HasOne("CoreApplication.Data.DataEntities.LoginUser", "Liker")
                        .WithMany("Likee")
                        .HasForeignKey("LikeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoreApplication.Data.DataEntities.LoginUser", "Likee")
                        .WithMany("Liker")
                        .HasForeignKey("LikerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Photo", b =>
                {
                    b.HasOne("CoreApplication.Data.DataEntities.LoginUser", "User")
                        .WithMany("Photos")
                        .HasForeignKey("LoginUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApplication.Data.DataEntities.Response", b =>
                {
                    b.HasOne("CoreApplication.Data.Models.Ad", "Ad")
                        .WithMany("Responses")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApplication.Data.Models.Ad", b =>
                {
                    b.HasOne("CoreApplication.Data.Models.Category")
                        .WithMany("Ads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
